In [75]:
### Importing libraries 

import numpy as np

import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

import scipy.optimize as opt
from sklearn import preprocessing

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

from sklearn.metrics import jaccard_similarity_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from scipy import stats

In [6]:
data = pd.read_csv('conversion_data.csv')

In [8]:
data.head(10)

country  age  new_user  source  total_pages_visited  converted
0      UK   25         1     Ads                    1          0
1      US   23         1     Seo                    5          0
2      US   28         1     Seo                    4          0
3   China   39         1     Seo                    5          0
4      US   30         1     Seo                    6          0
5      US   31         0     Seo                    1          0
6   China   27         1     Seo                    4          0
7      US   23         0     Ads                    4          0
8      UK   29         0  Direct                    4          0
9      US   25         0     Ads                    2          0

### Exploratory Data Analysis

In [11]:
### number of examples of each categories of conversion

data.groupby('converted').count()

country     age  new_user  source  total_pages_visited
converted                                                        
0           306000  306000    306000  306000               306000
1            10200   10200     10200   10200                10200

In [69]:
data.describe()

age       new_user  total_pages_visited      converted
count  316200.000000  316200.000000        316200.000000  316200.000000
mean       30.569858       0.685465             4.872966       0.032258
std         8.271802       0.464331             3.341104       0.176685
min        17.000000       0.000000             1.000000       0.000000
25%        24.000000       0.000000             2.000000       0.000000
50%        30.000000       1.000000             4.000000       0.000000
75%        36.000000       1.000000             7.000000       0.000000
max       123.000000       1.000000            29.000000       1.000000

In [63]:
data.corr()

age  new_user  total_pages_visited  converted
age                  1.000000  0.012343            -0.045922  -0.088797
new_user             0.012343  1.000000            -0.082541  -0.152374
total_pages_visited -0.045922 -0.082541             1.000000   0.528994
converted           -0.088797 -0.152374             0.528994   1.000000

In [76]:
pearson_coef, p_value = stats.pearsonr(data['new_user'], data['converted'])
print("The Pearson Correlation Coefficient between conversion and new user is", pearson_coef, " with a P-value of P =", p_value)  

The Pearson Correlation Coefficient is -0.15237386775904088  with a P-value of P = 0.0


In [77]:
pearson_coef, p_value = stats.pearsonr(data['age'], data['converted'])
print("The Pearson Correlation Coefficient between conversion and age is", pearson_coef, " with a P-value of P =", p_value)  

The Pearson Correlation Coefficient is -0.088797350840055  with a P-value of P = 0.0


In [78]:
pearson_coef, p_value = stats.pearsonr(data['total_pages_visited'], data['converted'])
print("The Pearson Correlation Coefficient between conversion and total pages visited is", pearson_coef, " with a P-value of P =", p_value)  

The Pearson Correlation Coefficient is 0.528993955018847  with a P-value of P = 0.0


#### The features "new user", "age", and "total pages visited" are correlated with conversion because the P-value < 0. Total pages visited is positively correlated while age and new user is negavtively correlated with conversion, as can be inferred from the Pearson Correlation Coefficient.

### Splitting the data into train-test sets to evaluate models 

In [30]:
Y=data[['converted']]
Y.head()

converted
0          0
1          0
2          0
3          0
4          0

In [32]:
X=data[['country','age','new_user','source','total_pages_visited']]
X.head()

country  age  new_user source  total_pages_visited
0      UK   25         1    Ads                    1
1      US   23         1    Seo                    5
2      US   28         1    Seo                    4
3   China   39         1    Seo                    5
4      US   30         1    Seo                    6

In [36]:
### train-test split to evaluate models

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(211854, 5)
(104346, 5)
(211854, 1)
(104346, 1)


### Logistic Regression classfier 

#### Since this is a classification problem, a logistic regression classifier seems most appropriate.  

In [90]:
LR = LogisticRegression(solver='liblinear').fit(X_train[['new_user']],Y_train)
LR

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [91]:
Yhat = LR.predict(X_test[['new_user']])
Yhat

array([0, 0, 0, ..., 0, 0, 0])

In [92]:
jaccard_similarity_score(Y_test, Yhat)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9685565330726621

In [87]:
LR1 = LogisticRegression(solver='liblinear').fit(X_train[['age']],Y_train)
LR1

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [95]:
Yhat1 = LR1.predict(X_test[['age']])
Yhat1

array([0, 0, 0, ..., 0, 0, 0])

In [96]:
jaccard_similarity_score(Y_test, Yhat1)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9685565330726621

In [100]:
LR2 = LogisticRegression(solver='liblinear').fit(X_train[['total_pages_visited']],Y_train)
LR2

/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [101]:
Yhat2 = LR2.predict(X_test[['total_pages_visited']])
Yhat2

array([0, 0, 0, ..., 0, 0, 0])

In [102]:
jaccard_similarity_score(Y_test, Yhat2)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


0.9832863741782147

#### Since the jaccard index is close to 1 for the features "new user", "age", and "total pages visited", the model is accurate. 

### Recommendations based on the correlations:

#### - focus on younger users and customers who are loyal who keep returning to the website - they tend to convert more than others. 